syntax = "proto3";

package order;

// This dictates the Go package name when generated
option go_package = "github.com/YOUR_GITHUB_USERNAME/AeroStore/api/proto";

// The Order Service Definition
service OrderService {
  // Creates a new order in the database
  rpc CreateOrder(CreateOrderRequest) returns (CreateOrderResponse);
  
  // Gets the status of an existing order
  rpc GetOrder(GetOrderRequest) returns (GetOrderResponse);
}

message OrderItem {
  string product_id = 1;
  int32 quantity = 2;
}

message CreateOrderRequest {
  string user_id = 1;
  repeated OrderItem items = 2;
}

message CreateOrderResponse {
  string order_id = 1;
  string status = 2;
}

message GetOrderRequest {
  string order_id = 1;
}

message GetOrderResponse {
  string order_id = 1;
  string user_id = 2;
  string status = 3;
}